<?php

namespace ToDoList\ListBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ToDoList\ListBundle\Entity\Task;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{

	public function getTasks($affichage = "tout", $authorId){
    	if($affichage == "tout") {
	    	$tasks = $this->findBy(
	    		array('author' => $authorId,
	    			'enabled' => true
	    		),
	    		array('updatedAt' => 'desc')
	    	);
    	}
    	else if($affichage == "en_attente") {

	    	$query = $this->createQueryBuilder('t')
		    	->where("t.author = :author")
		    	->andWhere("t.enabled = true")
		    	->andWhere("t.done = false");

		    // module pour la gestion des parenthèses dans la requête avec le query builder
    		$orModule = $query->expr()->orx()
	    		->add($query->expr()->gt('t.dueDate', "CURRENT_TIMESTAMP()")) // supérieur à la date actuelle
			    ->add($query->expr()->isNull('t.dueDate'));

			// On intègre le module dans la requête
		    $query->andWhere($orModule)
		    	->setParameter("author", $authorId)
		    	->orderBy("t.updatedAt", "DESC");

		    $tasks = $query->getQuery()->getResult();
    	}
    	else if($affichage == "terminees") {
	    	$query = $this->createQueryBuilder('t')
		    	->where("t.author = :author")
		    	->andWhere("t.enabled = true");

		    $orModule = $query->expr()->orx()
	    		->add($query->expr()->lt('t.dueDate', "CURRENT_TIMESTAMP()")) // inférieur à la date actuelle
			    ->add($query->expr()->eq('t.done', true));

		    $query->andWhere($orModule)
		    	->setParameter("author", $authorId)
		    	->orderBy("t.dueDate", "DESC");

		    $tasks = $query->getQuery()->getResult();
    	}
    	else if($affichage == "supprimees") {
	    	$query = $this->createQueryBuilder('t')
		    	->where("t.author = :author")
		    	->andWhere("t.enabled = false")
		    	->setParameter("author", $authorId)
		    	->orderBy("t.dueDate", "DESC")
		    	->getQuery();

		    $tasks = $query->getResult();
    	}

    	return $tasks;
	}

	private function countTasksType($filtre = 'tout', $authorId){
		if($filtre == "tout") {
	    	$tasks = $this->findBy(
	    		array('author' => $authorId,
	    			'enabled' => true
	    		)
	    	);

	    	$counter = count($tasks);
    	}
    	else if($filtre == "en_attente") {
	    	$query = $this->createQueryBuilder('t')
	    		->select('count(t.id)')
		    	->where("t.author = :author")
		    	->andWhere("t.enabled = true")
		    	->andWhere("t.done = false");

		    	// module pour la gestion des parenthèses dans la requête avec le query builder
    		$orModule = $query->expr()->orx()
	    		->add($query->expr()->gt('t.dueDate', "CURRENT_TIMESTAMP()")) // supérieur à la date actuelle
			    ->add($query->expr()->isNull('t.dueDate'));

		    $query->andWhere($orModule)
		    	->setParameter("author", $authorId);

		    $counter = $query->getQuery()->getSingleScalarResult();
    	}
    	else if($filtre == "terminees") {
	    	$query = $this->createQueryBuilder('t')
	    		->select('count(t.id)')
		    	->where("t.author = :author")
		    	->andWhere("t.enabled = true");

		    $orModule = $query->expr()->orx()
	    		->add($query->expr()->lt('t.dueDate', "CURRENT_TIMESTAMP()")) // inférieur à la date actuelle
			    ->add($query->expr()->eq('t.done', true));

		    $query->andWhere($orModule)
		    	->setParameter("author", $authorId);

		    $counter = $query->getQuery()->getSingleScalarResult();
    	}
    	else if($filtre == "supprimees") {
	    	$query = $this->createQueryBuilder('t')
	    		->select('count(t.id)')
		    	->where("t.author = :author")
		    	->andWhere("t.enabled = false")
		    	->setParameter("author", $authorId)
		    	->getQuery();

		    $counter = $query->getSingleScalarResult();
    	}

    	return $counter;
	}

	public function getCounterTasks($authorId){
		$counter = array('tout' => 0, 'en_attente' => 0, 'terminees' => 0);
		$counter['tout'] = $this->countTasksType('tout', $authorId);
		$counter['en_attente'] = $this->countTasksType('en_attente', $authorId);
		$counter['terminees'] = $this->countTasksType('terminees', $authorId);
		$counter['supprimees'] = $this->countTasksType('supprimees', $authorId);

		return $counter;
	}
}
