to_do_list_list:
    resource: 	"@ToDoListListBundle/Controller"
    type: 		annotation
    prefix:   	/listes

to_do_list_user:
    resource: 	"@ToDoListUserBundle/Controller"
    type: 		annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

KrumoBundle:
    resource: "@OodleKrumoBundle/Resources/config/routing/routing.yml"
    prefix:   /